title: "Tyler Joe Sims • Data Science Portfolio"
description: "Energy forecasting, automation, and analytics"
author: "Tyler Jpe Sims"
url: "https://tsims2.github.io"
baseurl: ""
collections:
  projects:
    output: true
    permalink: /projects/:name/
markdown: kramdown
